import {
  Blockquote,
  FigureImage,
  Heading,
  HeadingProps,
  Hr,
  Image,
  Link,
  Ol,
  Paragraph,
  Pre,
  Table,
  Ul,
} from './components';

export const MDXComponent = {
  p: Paragraph,
  h1: (props: HeadingProps) => <Heading as="h1" {...props} />,
  h2: (props: HeadingProps) => <Heading as="h2" {...props} />,
  h3: (props: HeadingProps) => <Heading as="h3" {...props} />,
  h4: (props: HeadingProps) => <Heading as="h4" {...props} />,
  h5: (props: HeadingProps) => <Heading as="h5" {...props} />,
  h6: (props: HeadingProps) => <Heading as="h6" {...props} />,
  hr: Hr,
  Image,
  a: Link,
  ul: Ul,
  ol: Ol,
  pre: Pre,
  table: Table,
  blockquote: Blockquote,
  FigureImage,
};
