/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appUsesRouteImport } from './routes/(app)/uses'
import { Route as appAboutRouteImport } from './routes/(app)/about'
import { Route as appUpdatesIndexRouteImport } from './routes/(app)/updates/index'
import { Route as appSnippetsIndexRouteImport } from './routes/(app)/snippets/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appWorksWorkIdRouteImport } from './routes/(app)/works/$workId'
import { Route as appUpdatesUpdateIdRouteImport } from './routes/(app)/updates/$updateId'
import { Route as appSnippetsSnippetIdRouteImport } from './routes/(app)/snippets/$snippetId'
import { Route as appAuthAuthRouteRouteImport } from './routes/(app)/auth/_auth/route'
import { Route as appAuthAuthRegisterRouteImport } from './routes/(app)/auth/_auth/register'
import { Route as appAuthAuthLoginRouteImport } from './routes/(app)/auth/_auth/login'

const appAuthRouteImport = createFileRoute('/(app)/auth')()

const appAuthRoute = appAuthRouteImport.update({
  id: '/(app)/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/(app)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appUsesRoute = appUsesRouteImport.update({
  id: '/(app)/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const appAboutRoute = appAboutRouteImport.update({
  id: '/(app)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const appUpdatesIndexRoute = appUpdatesIndexRouteImport.update({
  id: '/(app)/updates/',
  path: '/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const appSnippetsIndexRoute = appSnippetsIndexRouteImport.update({
  id: '/(app)/snippets/',
  path: '/snippets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appWorksWorkIdRoute = appWorksWorkIdRouteImport.update({
  id: '/(app)/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const appUpdatesUpdateIdRoute = appUpdatesUpdateIdRouteImport.update({
  id: '/(app)/updates/$updateId',
  path: '/updates/$updateId',
  getParentRoute: () => rootRouteImport,
} as any)
const appSnippetsSnippetIdRoute = appSnippetsSnippetIdRouteImport.update({
  id: '/(app)/snippets/$snippetId',
  path: '/snippets/$snippetId',
  getParentRoute: () => rootRouteImport,
} as any)
const appAuthAuthRouteRoute = appAuthAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => appAuthRoute,
} as any)
const appAuthAuthRegisterRoute = appAuthAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => appAuthAuthRouteRoute,
} as any)
const appAuthAuthLoginRoute = appAuthAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => appAuthAuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof appAboutRoute
  '/uses': typeof appUsesRoute
  '/': typeof appIndexRoute
  '/auth': typeof appAuthAuthRouteRouteWithChildren
  '/snippets/$snippetId': typeof appSnippetsSnippetIdRoute
  '/updates/$updateId': typeof appUpdatesUpdateIdRoute
  '/works/$workId': typeof appWorksWorkIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/snippets': typeof appSnippetsIndexRoute
  '/updates': typeof appUpdatesIndexRoute
  '/auth/login': typeof appAuthAuthLoginRoute
  '/auth/register': typeof appAuthAuthRegisterRoute
}
export interface FileRoutesByTo {
  '/about': typeof appAboutRoute
  '/uses': typeof appUsesRoute
  '/': typeof appIndexRoute
  '/auth': typeof appAuthAuthRouteRouteWithChildren
  '/snippets/$snippetId': typeof appSnippetsSnippetIdRoute
  '/updates/$updateId': typeof appUpdatesUpdateIdRoute
  '/works/$workId': typeof appWorksWorkIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/snippets': typeof appSnippetsIndexRoute
  '/updates': typeof appUpdatesIndexRoute
  '/auth/login': typeof appAuthAuthLoginRoute
  '/auth/register': typeof appAuthAuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/about': typeof appAboutRoute
  '/(app)/uses': typeof appUsesRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/auth': typeof appAuthRouteWithChildren
  '/(app)/auth/_auth': typeof appAuthAuthRouteRouteWithChildren
  '/(app)/snippets/$snippetId': typeof appSnippetsSnippetIdRoute
  '/(app)/updates/$updateId': typeof appUpdatesUpdateIdRoute
  '/(app)/works/$workId': typeof appWorksWorkIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/snippets/': typeof appSnippetsIndexRoute
  '/(app)/updates/': typeof appUpdatesIndexRoute
  '/(app)/auth/_auth/login': typeof appAuthAuthLoginRoute
  '/(app)/auth/_auth/register': typeof appAuthAuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/uses'
    | '/'
    | '/auth'
    | '/snippets/$snippetId'
    | '/updates/$updateId'
    | '/works/$workId'
    | '/api/auth/$'
    | '/snippets'
    | '/updates'
    | '/auth/login'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/uses'
    | '/'
    | '/auth'
    | '/snippets/$snippetId'
    | '/updates/$updateId'
    | '/works/$workId'
    | '/api/auth/$'
    | '/snippets'
    | '/updates'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/(app)/about'
    | '/(app)/uses'
    | '/(app)/'
    | '/(app)/auth'
    | '/(app)/auth/_auth'
    | '/(app)/snippets/$snippetId'
    | '/(app)/updates/$updateId'
    | '/(app)/works/$workId'
    | '/api/auth/$'
    | '/(app)/snippets/'
    | '/(app)/updates/'
    | '/(app)/auth/_auth/login'
    | '/(app)/auth/_auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appAboutRoute: typeof appAboutRoute
  appUsesRoute: typeof appUsesRoute
  appIndexRoute: typeof appIndexRoute
  appAuthRoute: typeof appAuthRouteWithChildren
  appSnippetsSnippetIdRoute: typeof appSnippetsSnippetIdRoute
  appUpdatesUpdateIdRoute: typeof appUpdatesUpdateIdRoute
  appWorksWorkIdRoute: typeof appWorksWorkIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  appSnippetsIndexRoute: typeof appSnippetsIndexRoute
  appUpdatesIndexRoute: typeof appUpdatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/auth': {
      id: '/(app)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof appAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/uses': {
      id: '/(app)/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof appUsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/about': {
      id: '/(app)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/updates/': {
      id: '/(app)/updates/'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof appUpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/snippets/': {
      id: '/(app)/snippets/'
      path: '/snippets'
      fullPath: '/snippets'
      preLoaderRoute: typeof appSnippetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/works/$workId': {
      id: '/(app)/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof appWorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/updates/$updateId': {
      id: '/(app)/updates/$updateId'
      path: '/updates/$updateId'
      fullPath: '/updates/$updateId'
      preLoaderRoute: typeof appUpdatesUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/snippets/$snippetId': {
      id: '/(app)/snippets/$snippetId'
      path: '/snippets/$snippetId'
      fullPath: '/snippets/$snippetId'
      preLoaderRoute: typeof appSnippetsSnippetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/auth/_auth': {
      id: '/(app)/auth/_auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof appAuthAuthRouteRouteImport
      parentRoute: typeof appAuthRoute
    }
    '/(app)/auth/_auth/register': {
      id: '/(app)/auth/_auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof appAuthAuthRegisterRouteImport
      parentRoute: typeof appAuthAuthRouteRoute
    }
    '/(app)/auth/_auth/login': {
      id: '/(app)/auth/_auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof appAuthAuthLoginRouteImport
      parentRoute: typeof appAuthAuthRouteRoute
    }
  }
}

interface appAuthAuthRouteRouteChildren {
  appAuthAuthLoginRoute: typeof appAuthAuthLoginRoute
  appAuthAuthRegisterRoute: typeof appAuthAuthRegisterRoute
}

const appAuthAuthRouteRouteChildren: appAuthAuthRouteRouteChildren = {
  appAuthAuthLoginRoute: appAuthAuthLoginRoute,
  appAuthAuthRegisterRoute: appAuthAuthRegisterRoute,
}

const appAuthAuthRouteRouteWithChildren =
  appAuthAuthRouteRoute._addFileChildren(appAuthAuthRouteRouteChildren)

interface appAuthRouteChildren {
  appAuthAuthRouteRoute: typeof appAuthAuthRouteRouteWithChildren
}

const appAuthRouteChildren: appAuthRouteChildren = {
  appAuthAuthRouteRoute: appAuthAuthRouteRouteWithChildren,
}

const appAuthRouteWithChildren =
  appAuthRoute._addFileChildren(appAuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appAboutRoute: appAboutRoute,
  appUsesRoute: appUsesRoute,
  appIndexRoute: appIndexRoute,
  appAuthRoute: appAuthRouteWithChildren,
  appSnippetsSnippetIdRoute: appSnippetsSnippetIdRoute,
  appUpdatesUpdateIdRoute: appUpdatesUpdateIdRoute,
  appWorksWorkIdRoute: appWorksWorkIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  appSnippetsIndexRoute: appSnippetsIndexRoute,
  appUpdatesIndexRoute: appUpdatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
