/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpdatesIndexRouteImport } from './routes/updates/index'
import { Route as SnippetsIndexRouteImport } from './routes/snippets/index'
import { Route as WorksWorkIdRouteImport } from './routes/works/$workId'
import { Route as UpdatesUpdateIdRouteImport } from './routes/updates/$updateId'
import { Route as SnippetsSnippetIdRouteImport } from './routes/snippets/$snippetId'
import { Route as DashboardUserRouteRouteImport } from './routes/dashboard/_user/route'
import { Route as DashboardAdminRouteRouteImport } from './routes/dashboard/_admin/route'
import { Route as DashboardUserIndexRouteImport } from './routes/dashboard/_user/index'
import { Route as UpdatesRUpdateIdRouteImport } from './routes/updates/r.$updateId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAuthResetPasswordRouteImport } from './routes/_auth/auth/reset-password'
import { Route as AuthAuthRegisterRouteImport } from './routes/_auth/auth/register'
import { Route as AuthAuthLoginRouteImport } from './routes/_auth/auth/login'
import { Route as AuthAuthForgotPasswordRouteImport } from './routes/_auth/auth/forgot-password'
import { Route as DashboardAdminAdminIndexRouteImport } from './routes/dashboard/_admin/admin/index'

const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIndexRoute = UpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsIndexRoute = SnippetsIndexRouteImport.update({
  id: '/snippets/',
  path: '/snippets/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksWorkIdRoute = WorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesUpdateIdRoute = UpdatesUpdateIdRouteImport.update({
  id: '/updates/$updateId',
  path: '/updates/$updateId',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsSnippetIdRoute = SnippetsSnippetIdRouteImport.update({
  id: '/snippets/$snippetId',
  path: '/snippets/$snippetId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserRouteRoute = DashboardUserRouteRouteImport.update({
  id: '/dashboard/_user',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/dashboard/_admin',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserIndexRoute = DashboardUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUserRouteRoute,
} as any)
const UpdatesRUpdateIdRoute = UpdatesRUpdateIdRouteImport.update({
  id: '/updates/r/$updateId',
  path: '/updates/r/$updateId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthResetPasswordRoute = AuthAuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthRegisterRoute = AuthAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthLoginRoute = AuthAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthForgotPasswordRoute = AuthAuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardAdminAdminIndexRoute =
  DashboardAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/uses': typeof UsesRoute
  '/dashboard': typeof DashboardUserRouteRouteWithChildren
  '/snippets/$snippetId': typeof SnippetsSnippetIdRoute
  '/updates/$updateId': typeof UpdatesUpdateIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/snippets': typeof SnippetsIndexRoute
  '/updates': typeof UpdatesIndexRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/register': typeof AuthAuthRegisterRoute
  '/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/updates/r/$updateId': typeof UpdatesRUpdateIdRoute
  '/dashboard/': typeof DashboardUserIndexRoute
  '/dashboard/admin': typeof DashboardAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/uses': typeof UsesRoute
  '/dashboard': typeof DashboardUserIndexRoute
  '/snippets/$snippetId': typeof SnippetsSnippetIdRoute
  '/updates/$updateId': typeof UpdatesUpdateIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/snippets': typeof SnippetsIndexRoute
  '/updates': typeof UpdatesIndexRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/register': typeof AuthAuthRegisterRoute
  '/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/updates/r/$updateId': typeof UpdatesRUpdateIdRoute
  '/dashboard/admin': typeof DashboardAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/uses': typeof UsesRoute
  '/dashboard/_admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/_user': typeof DashboardUserRouteRouteWithChildren
  '/snippets/$snippetId': typeof SnippetsSnippetIdRoute
  '/updates/$updateId': typeof UpdatesUpdateIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/snippets/': typeof SnippetsIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/_auth/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/_auth/auth/login': typeof AuthAuthLoginRoute
  '/_auth/auth/register': typeof AuthAuthRegisterRoute
  '/_auth/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/updates/r/$updateId': typeof UpdatesRUpdateIdRoute
  '/dashboard/_user/': typeof DashboardUserIndexRoute
  '/dashboard/_admin/admin/': typeof DashboardAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/uses'
    | '/dashboard'
    | '/snippets/$snippetId'
    | '/updates/$updateId'
    | '/works/$workId'
    | '/snippets'
    | '/updates'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/api/auth/$'
    | '/updates/r/$updateId'
    | '/dashboard/'
    | '/dashboard/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/uses'
    | '/dashboard'
    | '/snippets/$snippetId'
    | '/updates/$updateId'
    | '/works/$workId'
    | '/snippets'
    | '/updates'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/api/auth/$'
    | '/updates/r/$updateId'
    | '/dashboard/admin'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/uses'
    | '/dashboard/_admin'
    | '/dashboard/_user'
    | '/snippets/$snippetId'
    | '/updates/$updateId'
    | '/works/$workId'
    | '/snippets/'
    | '/updates/'
    | '/_auth/auth/forgot-password'
    | '/_auth/auth/login'
    | '/_auth/auth/register'
    | '/_auth/auth/reset-password'
    | '/api/auth/$'
    | '/updates/r/$updateId'
    | '/dashboard/_user/'
    | '/dashboard/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  UsesRoute: typeof UsesRoute
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardUserRouteRoute: typeof DashboardUserRouteRouteWithChildren
  SnippetsSnippetIdRoute: typeof SnippetsSnippetIdRoute
  UpdatesUpdateIdRoute: typeof UpdatesUpdateIdRoute
  WorksWorkIdRoute: typeof WorksWorkIdRoute
  SnippetsIndexRoute: typeof SnippetsIndexRoute
  UpdatesIndexRoute: typeof UpdatesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  UpdatesRUpdateIdRoute: typeof UpdatesRUpdateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/': {
      id: '/updates/'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/': {
      id: '/snippets/'
      path: '/snippets'
      fullPath: '/snippets'
      preLoaderRoute: typeof SnippetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$workId': {
      id: '/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/$updateId': {
      id: '/updates/$updateId'
      path: '/updates/$updateId'
      fullPath: '/updates/$updateId'
      preLoaderRoute: typeof UpdatesUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/$snippetId': {
      id: '/snippets/$snippetId'
      path: '/snippets/$snippetId'
      fullPath: '/snippets/$snippetId'
      preLoaderRoute: typeof SnippetsSnippetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_user': {
      id: '/dashboard/_user'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardUserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_admin': {
      id: '/dashboard/_admin'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_user/': {
      id: '/dashboard/_user/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardUserIndexRouteImport
      parentRoute: typeof DashboardUserRouteRoute
    }
    '/updates/r/$updateId': {
      id: '/updates/r/$updateId'
      path: '/updates/r/$updateId'
      fullPath: '/updates/r/$updateId'
      preLoaderRoute: typeof UpdatesRUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth/reset-password': {
      id: '/_auth/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthAuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/register': {
      id: '/_auth/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/login': {
      id: '/_auth/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/forgot-password': {
      id: '/_auth/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthAuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/_admin/admin/': {
      id: '/dashboard/_admin/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAuthForgotPasswordRoute: typeof AuthAuthForgotPasswordRoute
  AuthAuthLoginRoute: typeof AuthAuthLoginRoute
  AuthAuthRegisterRoute: typeof AuthAuthRegisterRoute
  AuthAuthResetPasswordRoute: typeof AuthAuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthForgotPasswordRoute: AuthAuthForgotPasswordRoute,
  AuthAuthLoginRoute: AuthAuthLoginRoute,
  AuthAuthRegisterRoute: AuthAuthRegisterRoute,
  AuthAuthResetPasswordRoute: AuthAuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardAdminRouteRouteChildren {
  DashboardAdminAdminIndexRoute: typeof DashboardAdminAdminIndexRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminAdminIndexRoute: DashboardAdminAdminIndexRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardUserRouteRouteChildren {
  DashboardUserIndexRoute: typeof DashboardUserIndexRoute
}

const DashboardUserRouteRouteChildren: DashboardUserRouteRouteChildren = {
  DashboardUserIndexRoute: DashboardUserIndexRoute,
}

const DashboardUserRouteRouteWithChildren =
  DashboardUserRouteRoute._addFileChildren(DashboardUserRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  UsesRoute: UsesRoute,
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardUserRouteRoute: DashboardUserRouteRouteWithChildren,
  SnippetsSnippetIdRoute: SnippetsSnippetIdRoute,
  UpdatesUpdateIdRoute: UpdatesUpdateIdRoute,
  WorksWorkIdRoute: WorksWorkIdRoute,
  SnippetsIndexRoute: SnippetsIndexRoute,
  UpdatesIndexRoute: UpdatesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  UpdatesRUpdateIdRoute: UpdatesRUpdateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
