/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpdatesIndexRouteImport } from './routes/updates/index'
import { Route as SnippetsIndexRouteImport } from './routes/snippets/index'
import { Route as WorksWorkIdRouteImport } from './routes/works/$workId'
import { Route as UpdatesUpdateIdRouteImport } from './routes/updates/$updateId'
import { Route as SnippetsSnippetIdRouteImport } from './routes/snippets/$snippetId'
import { Route as ImagesSplatRouteImport } from './routes/_images/$'

const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIndexRoute = UpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsIndexRoute = SnippetsIndexRouteImport.update({
  id: '/snippets/',
  path: '/snippets/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksWorkIdRoute = WorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesUpdateIdRoute = UpdatesUpdateIdRouteImport.update({
  id: '/updates/$updateId',
  path: '/updates/$updateId',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsSnippetIdRoute = SnippetsSnippetIdRouteImport.update({
  id: '/snippets/$snippetId',
  path: '/snippets/$snippetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesSplatRoute = ImagesSplatRouteImport.update({
  id: '/_images/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/uses': typeof UsesRoute
  '/$': typeof ImagesSplatRoute
  '/snippets/$snippetId': typeof SnippetsSnippetIdRoute
  '/updates/$updateId': typeof UpdatesUpdateIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/snippets': typeof SnippetsIndexRoute
  '/updates': typeof UpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/uses': typeof UsesRoute
  '/$': typeof ImagesSplatRoute
  '/snippets/$snippetId': typeof SnippetsSnippetIdRoute
  '/updates/$updateId': typeof UpdatesUpdateIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/snippets': typeof SnippetsIndexRoute
  '/updates': typeof UpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/uses': typeof UsesRoute
  '/_images/$': typeof ImagesSplatRoute
  '/snippets/$snippetId': typeof SnippetsSnippetIdRoute
  '/updates/$updateId': typeof UpdatesUpdateIdRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/snippets/': typeof SnippetsIndexRoute
  '/updates/': typeof UpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/uses'
    | '/$'
    | '/snippets/$snippetId'
    | '/updates/$updateId'
    | '/works/$workId'
    | '/snippets'
    | '/updates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/uses'
    | '/$'
    | '/snippets/$snippetId'
    | '/updates/$updateId'
    | '/works/$workId'
    | '/snippets'
    | '/updates'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/uses'
    | '/_images/$'
    | '/snippets/$snippetId'
    | '/updates/$updateId'
    | '/works/$workId'
    | '/snippets/'
    | '/updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  UsesRoute: typeof UsesRoute
  ImagesSplatRoute: typeof ImagesSplatRoute
  SnippetsSnippetIdRoute: typeof SnippetsSnippetIdRoute
  UpdatesUpdateIdRoute: typeof UpdatesUpdateIdRoute
  WorksWorkIdRoute: typeof WorksWorkIdRoute
  SnippetsIndexRoute: typeof SnippetsIndexRoute
  UpdatesIndexRoute: typeof UpdatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/': {
      id: '/updates/'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/': {
      id: '/snippets/'
      path: '/snippets'
      fullPath: '/snippets'
      preLoaderRoute: typeof SnippetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$workId': {
      id: '/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/$updateId': {
      id: '/updates/$updateId'
      path: '/updates/$updateId'
      fullPath: '/updates/$updateId'
      preLoaderRoute: typeof UpdatesUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/$snippetId': {
      id: '/snippets/$snippetId'
      path: '/snippets/$snippetId'
      fullPath: '/snippets/$snippetId'
      preLoaderRoute: typeof SnippetsSnippetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_images/$': {
      id: '/_images/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof ImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  UsesRoute: UsesRoute,
  ImagesSplatRoute: ImagesSplatRoute,
  SnippetsSnippetIdRoute: SnippetsSnippetIdRoute,
  UpdatesUpdateIdRoute: UpdatesUpdateIdRoute,
  WorksWorkIdRoute: WorksWorkIdRoute,
  SnippetsIndexRoute: SnippetsIndexRoute,
  UpdatesIndexRoute: UpdatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
